const voterModel = require('../models/voterModel');
const candidateModel = require('../models/candidateModel');
const { NotFoundError, ForbiddenError, ValidationError } = require('../utils/errors');

function tenant(req) {
    if (!req.candidateId) throw new ForbiddenError('No candidate selected');
    return req.candidateId;
}

async function getById(req, res) {
    const voter = await voterModel.findById(tenant(req), req.params.voter_id);
    if (!voter) throw new NotFoundError('Voter not found');
    res.json({ success: true, voter });
}

/**
 * GET /api/voters/geo-options?wards=১৪,১৫
 * Ward + voter-area options for the multi-select navigation. Respects volunteer
 * ward/area restrictions. Areas are scoped to the requested wards.
 */
async function geoOptions(req, res) {
    const cid = tenant(req);
    const requestedWards = (req.query.wards || '').split(',').map((s) => s.trim()).filter(Boolean);
    const allowedWards = req.user?.allowed_wards;
    const allowedAreas = req.user?.allowed_voter_areas;

    let wards = await voterModel.geoWardOptions(cid);
    if (allowedWards?.length) wards = wards.filter((w) => allowedWards.includes(w.value));

    let areaWards = requestedWards;
    if (allowedWards?.length) {
        areaWards = (areaWards.length ? areaWards : allowedWards).filter((w) => allowedWards.includes(w));
    }
    let areas = await voterModel.geoAreaOptions(cid, areaWards);
    if (allowedAreas?.length) areas = areas.filter((a) => allowedAreas.includes(a.value));

    res.json({ success: true, wards, voter_areas: areas });
}

async function search(req, res) {
    const limit = req.query.limit ? parseInt(req.query.limit, 10) : 50;
    const voters = await voterModel.search(tenant(req), req.params.query, { limit });
    res.json({ success: true, voters });
}

async function byVillage(req, res) {
    const { village_id } = req.params;
    const limit = req.query.limit ? parseInt(req.query.limit, 10) : 1000;
    const offset = req.query.offset ? parseInt(req.query.offset, 10) : 0;
    const voters = await voterModel.byVillage(tenant(req), village_id, { limit, offset });
    res.json({ success: true, voters });
}

async function byVoterArea(req, res) {
    const voters = await voterModel.byVoterArea(tenant(req), req.params.voter_area, {
        limit: parseInt(req.query.limit || 1000, 10),
        offset: parseInt(req.query.offset || 0, 10),
    });
    res.json({ success: true, voters });
}

async function byVoterAreas(req, res) {
    const { areas = [], status, search, limit, offset } = req.body || {};
    const result = await voterModel.byVoterAreas(tenant(req), {
        areas,
        status,
        search,
        limit: limit ? parseInt(limit, 10) : 500,
        offset: offset ? parseInt(offset, 10) : 0,
    });
    res.json({ success: true, ...result });
}

async function listVoterAreas(req, res) {
    res.json({ success: true, voter_areas: await voterModel.listVoterAreas(tenant(req)) });
}

async function voterAreaStats(req, res) {
    const stats = await voterModel.voterAreaStats(tenant(req), req.params.voter_area);
    res.json({ success: true, stats });
}

async function aggregatedStats(req, res) {
    const groupBy = req.body?.group_by || 'union';
    const stats = await voterModel.aggregatedStatistics(tenant(req), { groupBy });
    res.json({ success: true, stats });
}

/**
 * POST /api/voters/filtered
 *   Body: {
 *     filters: { gender: [...] },   // user-facing — validated against filter_config
 *     scope:   { ward: '৫২' },      // geo-nav scope — safe keys only, bypasses filter_config
 *     status, search, limit, offset
 *   }
 *
 * scope keys allowed: 'ward', 'voter_area' (handled via the FILTERS map in voterModel).
 * scope is generated by the GeoNavigator / building click, not user input.
 */
async function filtered(req, res) {
    const candidateId = tenant(req);
    const { filters = {}, scope = {}, status, search, search_bn, limit, offset, stats_only } = req.body || {};

    // Validate user-facing filter keys against filter_config
    const candidate = await candidateModel.findById(candidateId);
    const specs = candidate?.filter_config || [];
    const allowed = new Set(specs.map((f) => f.key));
    for (const key of Object.keys(filters)) {
        if (!allowed.has(key)) {
            throw new ValidationError(`Filter '${key}' is not configured for this candidate`);
        }
    }

    // scope keys are system-generated — only allow known safe keys
    const SCOPE_SAFE = new Set(['ward', 'voter_area']);
    const safeScope = {};
    for (const [k, v] of Object.entries(scope)) {
        if (SCOPE_SAFE.has(k) && v != null && v !== '') safeScope[k] = v;
    }

    // Enforce ward restriction for volunteers: allowed_wards in JWT limits what ward can be requested.
    const allowedWards = req.user?.allowed_wards;
    if (allowedWards?.length) {
        if (safeScope.ward && !allowedWards.includes(safeScope.ward)) {
            throw new ForbiddenError('Ward not in your allowed wards');
        }
        // If no ward scoped yet, force to first allowed ward so they can't see all wards.
        if (!safeScope.ward) {
            safeScope.ward = allowedWards[0];
        }
    }

    // Finer voter-area restriction (volunteers assigned specific voter areas — #12).
    const allowedAreas = req.user?.allowed_voter_areas;
    if (allowedAreas?.length) {
        if (safeScope.voter_area && !allowedAreas.includes(safeScope.voter_area)) {
            throw new ForbiddenError('Voter area not in your allowed areas');
        }
        if (!safeScope.voter_area) {
            safeScope.voter_area = allowedAreas.length === 1 ? allowedAreas[0] : allowedAreas;
        }
    }

    // Merge: scope is broader context, filters are user refinements
    const merged = { ...safeScope, ...filters };

    const result = await voterModel.findByFilters(candidateId, {
        filters: merged,
        specs,
        status,
        search,
        searchBn: search_bn || null,
        limit: limit ? Math.min(parseInt(limit, 10) || 500, 2000) : 500,
        offset: offset ? parseInt(offset, 10) : 0,
        politicalCandidateId: req.user?.political_candidate_id || null,
        statsOnly: !!stats_only,
    });
    res.json({ success: true, ...result });
}

/** GET /api/voters/attribute-keys — distinct voter attribute columns for the filter designer */
async function attributeKeys(req, res) {
    res.json({ success: true, keys: await voterModel.attributeKeys(tenant(req)) });
}

/**
 * POST /api/voters/area-options
 * Body: { scope: { ward: '৫২' } }
 * Returns distinct voter_area_names scoped to the given ward (or all if no ward).
 */
async function areaOptions(req, res) {
    const candidateId = tenant(req);
    const { scope = {} } = req.body || {};
    const ward = scope.ward || undefined;
    const areas = await voterModel.listVoterAreasByScope(candidateId, { ward });
    res.json({ success: true, areas });
}

module.exports = {
    getById,
    geoOptions,
    search,
    byVillage,
    byVoterArea,
    byVoterAreas,
    filtered,
    listVoterAreas,
    voterAreaStats,
    aggregatedStats,
    attributeKeys,
    areaOptions,
};
